/**
	* Main view module
*/

/*#include "/views/SpecialActionsView.pwn"
#include "/views/UserView.pwn"
#include "/views/JobView.pwn"
#include "/views/VehicleView.pwn"
#include "/views/AirdropView.pwn"
#include "/views/NightclubView.pwn"
#include "/views/BunkerView.pwn"
#include "/views/OfficeView.pwn"
#include "/views/CrewView.pwn"
#include "/views/AdminView.pwn"
#include "/views/CashpointView.pwn"
#include "/views/HeistsView.pwn"
#include "/views/TerrorbyteView.pwn"
#include "/views/CasinoView.pwn"
#include "/views/GangAttackView.pwn"
#include "/views/MinigameView.pwn"
#include "/views/SurvivalView.pwn"
#include "/views/EventView.pwn"
#include "/views/PhoneView.pwn"
#include "/views/MissionView.pwn"
#include "/views/GPSView.pwn"
#include "/views/BrowserView.pwn"
#include "/views/ApartmentsView.pwn"
#include "/views/PegasusView.pwn"
#include "/views/SecuroServView.pwn"
#include "/views/YachtView.pwn"
#include "/views/FlightSchoolView.pwn"
#include "/views/GangzoneView.pwn"
#include "/views/OrgView.pwn"
#include "/views/MapsView.pwn"
#include "/views/UIView.pwn"
#include "/views/UserZoneView.pwn"*/